add yukichant command
theoremoon/ShellgeiBot-Image pull request #48
Opened 2019-08-11 22:00 UTC by amanoese

自作のマンドですみませんが、yukichantコマンドの追加をしていただけないでしょうか。

## Usage

###  genarate

```bash
$ chant
冠を御手を絢爛汚れ。我を意思に雫よ現れよ。仕打ち契約に羽根よ刻み。此処に剣に貫き。
```

### encode
```bash
$ echo -n こんにちは | chant
雫よ狭間の剣に渡れ。狭霧剣に雫よ囚われ。光を雫よ狭間の触れ。雫よ狭間の澄ませ。
```
### decode
```bash
$ echo 雫よ狭間の剣に渡れ。狭霧剣に雫よ囚われ。光を雫よ狭間の触れ。雫よ狭間の澄ませ。 | chant -d
こんにちは
```

---
まだまだ未完成でオプションも少なく生成する文言も呪文ぽくなってないですが、
今後も開発を続けていくのでMergeしていただけると幸いです。

2019-08-11 22:47 UTC, theoremoon requested changes
シェル芸bot環境だとうまく動かないみたいです。申し訳ありませんが修正をお願いします（デコード時に `Object.fromEntries is not a function` というエラーが出てるっぽい？

2019-08-11 22:48 UTC, theoldmoon0602 commented
あとテストケースの `echo -e` は `echo -n` ではないでしょうか

2019-08-12 04:33 UTC, amanoese commented
yukichantをv10.15.2で動作するよう修正しました。
お手数ですがCIを動かしていただいてもよろしいでしょうか？

2019-08-12 04:50 UTC, theoremoon approved these changes

2019-08-12 05:12 UTC, theoldmoon0602 commented
チェック通りました！　OKです！

2019-08-12 05:12 UTC, merged

2019-08-12 05:41 UTC, amanoese commented
MasterのCircleCIのBuildが落ちてるみたいです。
今回の修正に関係なければReturn Workflowしていたけると幸いです。